### ISSUE TITLE
Completion of Post

### ISSUE THREAD

**Issue by George-Gauvierre6** [UCC-SMD/Norfleet#10]
We need to complete post.php -- since the whole project is supposed to be post.php
Hopefully it shouldn't take long - just make sure upload the SQL database change to the existing sql command code.

**Comment by camranhansen** [comment]
"Oh don't worry you just need to change a bit of code"

Thanks charlie. It's not like I have been working on this for the past 2
hours.

On Wed, May 18, 2016 at 10:49 PM, George-Gauvierre6 <
notifications@github.com> wrote:

> We need to complete post.php -- since the whole project is supposed to be
> post.php
> Shouldn't take long - just make sure upload the SQL database change to the
> existing sql command code.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/UCC-SMD/Norfleet/issues/10

## 

Thanks,

Camran Hansen
Jacksons FY

**Comment by J0hnMace** [comment]
Don't worry mate. It may look like we're sailing in/into dark waters, but we're nearing the end of our voyage. It's all smooth sailing from here.

**Comment by George-Gauvierre6** [comment]
As an aside: using quotations when falsely quoting someone is technically illegal - since I never said "don't worry" nor "change a bit of code".
Don't worry though, I'll keep my lawyers on their leash for now.

**Comment by camranhansen** [comment]
Charlie (or campbell if he is alive). Please put a banner at the top of
each file and comment code. For the love of god don't make me do all the
code and also comment it. : (

On Wed, May 18, 2016 at 11:06 PM, George-Gauvierre6 <
notifications@github.com> wrote:

> As an aside: using quotations when falsely quoting someone is technically
> illegal - since I never said "don't worry" nor "change a bit of code".
> Don't worry though, I'll keep my lawyers on their leash for now.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/UCC-SMD/Norfleet/issues/10#issuecomment-220216632

## 

Thanks,

Camran Hansen
Jacksons FY

**Comment by George-Gauvierre6** [comment]
We're both getting to that
