### ISSUE TITLE
Font Awesome not loading

### ISSUE THREAD

**Issue by J0hnMace** [UCC-SMD/Norfleet#2]
If you look at the index.php page you'll notice all the font Awesome stuff is commented out. If you could fix it (by un-commenting it and loading the icons) it would be greatly appreciated.

**Comment by JamesThomasChaplin** [comment]
Hello, just include

`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css">` This will use the online library

**Comment by J0hnMace** [comment]
Thank you so much. We have working icons now.

**Comment by J0hnMace** [comment]
Out of curiosity, do you know why it didn't work when we tried to load the stylesheet locally?
