### ISSUE TITLE
Wall page not complete

### ISSUE THREAD

**Issue by J0hnMace** [UCC-SMD/Norfleet#4]
We need to add some polish to the page that a user sees if they access the website but are not logged in. Also, we will probably need to combine this with FraggrenadeKittten's register_beta.php code. Do you want to do this or should I?

**Comment by camranhansen** [comment]
Hold off on combining them until the weekend because it is not done.

On Mon, May 9, 2016 at 4:00 PM, John Mace notifications@github.com wrote:

> We need to add some polish to the page that a user sees if they access the
> website but are not logged in. Also, we will probably need to combine this
> with FraggrenadeKittten's register_beta.php code. Do you want to do this or
> should I?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/UCC-SMD/Norfleet/issues/4

## 

Thanks,

Camran Hansen
Jacksons FY

**Comment by J0hnMace** [comment]
Acknowledged and understood. Let me know if you need any help in the meantime. Is it ok if I make front-end for the login page once i'm done the front-end for the other pages? I'll hopefully get to that before the weekend.

**Comment by camranhansen** [comment]
Yes. Keep in mind that the login form may have some more features.

On Mon, May 9, 2016 at 7:42 PM, John Mace notifications@github.com wrote:

> Acknowledged and understood. Let me know if you need any help in the
> meantime. Is it ok if I make front-end for the login page once i'm done the
> front-end for the other pages? I'll hopefully get to that before the
> weekend.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/UCC-SMD/Norfleet/issues/4#issuecomment-218011544

## 

Thanks,

Camran Hansen
Jacksons FY

**Comment by J0hnMace** [comment]
Would those features make their way into the logout process as well?

**Comment by camranhansen** [comment]
No. Logout is just 1 button I think

On Mon, May 9, 2016 at 9:13 PM, John Mace notifications@github.com wrote:

> Would those features make their way into the logout process as well?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/UCC-SMD/Norfleet/issues/4#issuecomment-218034110

## 

Thanks,

Camran Hansen
Jacksons FY
