### ISSUE TITLE
Login page incomplete

### ISSUE THREAD

**Issue by J0hnMace** [UCC-SMD/Norfleet#7]
You know what needs to be done.

**Comment by George-Gauvierre6** [comment]
And be sure to link it to the index.html

**Comment by J0hnMace** [comment]
Do I implement register.php or register_beta.php?

**Comment by George-Gauvierre6** [comment]
I was under the impression register_beta is Camran's work in progress, so I
would use register.

**Comment by J0hnMace** [comment]
I'll try and get in touch with him and ask him just to be sure, but I was going to fall back onto register.php if I couldn't reach him by tomorrow's class.
